### ISSUE TITLE
希望更换 systemd 检测方式 

### ISSUE THREAD

**Issue by kobe-koto** [GenshinMinecraft/ak_monitor_client_rs#2]
通过读取 `/proc/1/comm` 可以获得较为准确的 init system.
systemd 通常结果是 `systemd`
openrc 通常结果是 `init` 或 `openrc`

**Comment by GenshinMinecraft** [comment]
好主意，一般我都直接判定systemctl是否存在的

**Comment by GenshinMinecraft** [comment]
Fixed
