### ISSUE TITLE
希望增加 OpenRC 服务的部署

### ISSUE THREAD

**Issue by kobe-koto** [GenshinMinecraft/ak_monitor_client_rs#3]
OpenRC 主要用于 Alpine 系统

可以参考这个示例

```bash
#!/sbin/openrc-run

command=/usr/bin/ak_monitor_client_rs
command_args="$ARGS"
pidfile=/run/$SERVICE_NAME.pid
description="Akile Monitor Slave Client (Rust) Service"

depend() {
    need net
    after firewall
}

start() {
    ebegin "Starting $SERVICE_NAME"
    start-stop-daemon --start --background --make-pidfile --pidfile \$pidfile --exec \$command -- \$command_args
    eend \$?
}

stop() {
    ebegin "Stopping $SERVICE_NAME"
    start-stop-daemon --stop --pidfile \$pidfile
    eend \$?
}

restart() {
    stop
    start
}
```

安装需要

```bash
chmod +x $SERVICE_FILE              # 将服务文件标记为可执行
rc-update add $SERVICE_NAME default # 开机自启
/etc/init.d/$SERVICE_NAME start     # 启动服务
```

而卸载需要

```bash
/etc/init.d/$SERVICE_NAME stop      # 停止服务
rc-update del $SERVICE_NAME default # 关闭开机自启
rm -rf /etc/init.d/$SERVICE_NAME    # 删除服务文件
```

**Comment by kobe-koto** [comment]
OpenRC 的检测参考 #2

**Comment by GenshinMinecraft** [comment]
提醒我了，还得写个卸载

还有 start() stop() 里面都是 Bash 命令吗

**Comment by kobe-koto** [comment]
> 提醒我了，还得写个卸载
> 
> 还有 start() stop() 里面都是 Bash 命令吗

我觉得不太像 可以查查 OpenRC 文档,
这些我也是别的地方抄来的, 勉强能用说是

**Comment by GenshinMinecraft** [comment]
> > 提醒我了，还得写个卸载
> > 还有 start() stop() 里面都是 Bash 命令吗
> 
> 我觉得不太像 可以查查 OpenRC 文档, 这些我也是别的地方抄来的, 勉强能用说是

看起来只要更改line3的命令就好了 我找个alpine试试

**Comment by GenshinMinecraft** [comment]
> OpenRC 主要用于 Alpine 系统
> 
> 可以参考这个示例
> 
> ```shell
> #!/sbin/openrc-run
> 
> command=/usr/bin/ak_monitor_client_rs
> command_args="$ARGS"
> pidfile=/run/$SERVICE_NAME.pid
> description="Akile Monitor Slave Client (Rust) Service"
> 
> depend() {
>     need net
>     after firewall
> }
> 
> start() {
>     ebegin "Starting $SERVICE_NAME"
>     start-stop-daemon --start --background --make-pidfile --pidfile \$pidfile --exec \$command -- \$command_args
>     eend \$?
> }
> 
> stop() {
>     ebegin "Stopping $SERVICE_NAME"
>     start-stop-daemon --stop --pidfile \$pidfile
>     eend \$?
> }
> 
> restart() {
>     stop
>     start
> }
> ```
> 
> 安装需要
> 
> ```shell
> chmod +x $SERVICE_FILE              # 将服务文件标记为可执行
> rc-update add $SERVICE_NAME default # 开机自启
> /etc/init.d/$SERVICE_NAME start     # 启动服务
> ```
> 
> 而卸载需要
> 
> ```shell
> /etc/init.d/$SERVICE_NAME stop      # 停止服务
> rc-update del $SERVICE_NAME default # 关闭开机自启
> rm -rf /etc/init.d/$SERVICE_NAME    # 删除服务文件
> ```

如果可以的话，麻烦下载最新版本试一下 openrc 的安装功能，我没有测试过

**Comment by kobe-koto** [comment]
啊啊啊啊啊这个示例是我直接从我写的安装脚本里抄出来的, 里面的转义字符没删掉, 所有的 `\$` 应该都得是 `$`, 然后所有的 `$SERVICE_NAME` 应该都得改成 `akile_monitor_client_rs`

**Comment by kobe-koto** [comment]
> 啊啊啊啊啊这个示例是我直接从我写的安装脚本里抄出来的, 里面的转义字符没删掉, 所有的 `\$` 应该都得是 `$`, 然后所有的 `$SERVICE_NAME` 应该都得改成 `akile_monitor_client_rs`

大致试了一下这样改完后好像没问题

**Comment by kobe-koto** [comment]
凭感觉修了一下发了个 pr 请 review (((

**Comment by GenshinMinecraft** [comment]
重试一下吧，不是很了解 openrc的配置

**Comment by kobe-koto** [comment]
OpenRC 服务配置是没有问题的, 但是安装过程中自动启动时会报错 `Text file busy (os error 26)` (而且并未实际启动), 需要安装完成后手动执行 `rc-service akile_monitor_client_rs start`

**Comment by GenshinMinecraft** [comment]
> OpenRC 服务配置是没有问题的, 但是安装过程中自动启动时会报错 `Text file busy (os error 26)` (而且并未实际启动), 需要安装完成后手动执行 `rc-service akile_monitor_client_rs start`

我大概知道了

**Comment by GenshinMinecraft** [comment]
麻烦再试一下

**Comment by kobe-koto** [comment]
其实效果是一样的 昨天晚上试过了

**Comment by GenshinMinecraft** [comment]
[d836aca](https://github.com/GenshinMinecraft/ak_monitor_client_rs/commit/d836aca4f2322b0b804eb9f26552e13b6c1237d7) 给自动启动干了，改为让用户手动输入

我也不知道什么原因
