### ISSUE TITLE
系统名显示太长，影响显示面板美观度

### ISSUE THREAD

**Issue by TorBoxM** [GenshinMinecraft/ak_monitor_client_rs#4]
以debian12.8为例，S端和C端以及FE都为最新版本
官方版：debian 12.8
RS版：Debian GNU/Linux 12 (bookworm) 6.1.0-28-amd64

目前官方版C端在重启S端或者反代软件（如nginx）后必须重启C端才能连接，RS版C端不用重启会自动连接，这点好评。

**Comment by TorBoxM** [comment]
刚刚测试还发现一点：
网速上传/下载和流量in/out显示与实际情况刚好是反的

**Comment by GenshinMinecraft** [comment]
> 刚刚测试还发现一点： 网速上传/下载和流量in/out显示与实际情况刚好是反的

坏了 之前我也发现是反的，然后换过来了，然后又是反的了

**Comment by GenshinMinecraft** [comment]
> 以debian12.8为例，S端和C端以及FE都为最新版本 官方版：debian 12.8 RS版：Debian GNU/Linux 12 (bookworm) 6.1.0-28-amd64
> 
> 目前官方版C端在重启S端或者反代软件（如nginx）后必须重启C端才能连接，RS版C端不用重启会自动连接，这点好评。

有关于这个，我个人觉得如歌实在太长的话可以给后面的内核版本删了，前面是系统库获取的

**Comment by TorBoxM** [comment]
> > 以debian12.8为例，S端和C端以及FE都为最新版本 官方版：debian 12.8 RS版：Debian GNU/Linux 12 (bookworm) 6.1.0-28-amd64
> > 目前官方版C端在重启S端或者反代软件（如nginx）后必须重启C端才能连接，RS版C端不用重启会自动连接，这点好评。
> 
> 有关于这个，我个人觉得如歌实在太长的话可以给后面的内核版本删了，前面是系统库获取的

对于使用倒不影响，只是刚好在目前这个前端上面显示与整体不协调

**Comment by GenshinMinecraft** [comment]
> > > 以debian12.8为例，S端和C端以及FE都为最新版本 官方版：debian 12.8 RS版：Debian GNU/Linux 12 (bookworm) 6.1.0-28-amd64
> > > 目前官方版C端在重启S端或者反代软件（如nginx）后必须重启C端才能连接，RS版C端不用重启会自动连接，这点好评。
> > 
> > 
> > 有关于这个，我个人觉得如歌实在太长的话可以给后面的内核版本删了，前面是系统库获取的
> 
> 对于使用倒不影响，只是刚好在目前这个前端上面显示与整体不协调

确实有点 但是详细点也不是坏处（？）
其实真要改可以去前端让主页默认不显示系统，我并不认为系统是一个需要显示在主页的信息

**Comment by TorBoxM** [comment]
> > > > 以debian12.8为例，S端和C端以及FE都为最新版本 官方版：debian 12.8 RS版：Debian GNU/Linux 12 (bookworm) 6.1.0-28-amd64
> > > > 目前官方版C端在重启S端或者反代软件（如nginx）后必须重启C端才能连接，RS版C端不用重启会自动连接，这点好评。
> > > 
> > > 
> > > 有关于这个，我个人觉得如歌实在太长的话可以给后面的内核版本删了，前面是系统库获取的
> > 
> > 
> > 对于使用倒不影响，只是刚好在目前这个前端上面显示与整体不协调
> 
> 确实有点 但是详细点也不是坏处（？） 其实真要改可以去前端让主页默认不显示系统，我并不认为系统是一个需要显示在主页的信息

这个切实，什么系统自己都很清楚。
